### ISSUE TITLE
DL2 has unwanted "PC speaker type beep" 

### ISSUE THREAD

**Issue by BLohman66** [DavidGriffith/daphne#1]
Hi.  I just discovered Daphne today and love it!  Ran through DL first and it worked great all the way through to the final sequence... no issues at all.  Tried to run DL2 and it makes these super loud beeps like an old PC speaker (during the boot up messages, during the move indications, and during all the selecting within the service mode).  I could not figure out how to turn these beeps off and it's really annoying during game play that it keeps beeping.  I'm sure that I'm just missing a setting somewhere... but I can't figure it out.  I'm playing DL2 v3.19.  Also... Daphne didn't seem to want to import my Space Ace disk.  Any ideas/suggestions?

Thanks

**Comment by DavidGriffith** [comment]
You might have better luck with https://github.com/btolab/hypseus.  @btolab forked this repo and did a lot of work to modernize it and fix bugs.  The disk importation functionality is specific to the version obtained at http://www.daphne-emu.com.  To get your disk imported, I suggest using that just long enough to get the decrypted disk data.
