### ISSUE TITLE
[Singe] Timegal & Ninja Hayate Shutdown issues

### ISSUE THREAD

**Issue by HoJo215** [DavidGriffith/daphne#16]
These two games seem to shut down when I press the start button.

Here goes the output error:

`h@h-NUC8i7BEH:~/.daphne$ '/home/h/.daphne/singe.sh' timegal
Singe Launcher : Script dir is /home/h/.daphne
--DAPHNE version 1.0.13.1
--Command line is: ./daphne.bin singe vldp -framefile /home/h/.daphne/singe/timegal/timegal.txt -script /home/h/.daphne/singe/timegal/timegal.singe -homedir /home/h/.daphne -datadir /home/h/.daphne -sound_buffer 2048 -noserversend -x 800 -y 600 
--CPU : UnknownCPU 0 MHz || Mem : 4096 megs
--OS : Linux 5.5 || Video : Unknown video
--OpenGL: Compiled In
--RGB2YUV Function: C
--Line Blending Function: C
--Audio Mixing Function: C
Setting alternate home dir:
/home/h/.daphne
Setting sound buffer size to 2048
Setting screen width to 800
Setting screen height to 600
Set 800x600 at 32 bpp with flags: 0
Initializing sound system ... 
WARNING : requested 2048 samples for sound buffer, but got 1024 samples
Joystick #0 was successfully opened
Remapping input ...
button:0 mapped to KEY_BUTTON1 
button:1 mapped to KEY_BUTTON2 
button:2 mapped to KEY_BUTTON3 
button:3 mapped to KEY_PAUSE 
button:4 mapped to KEY_SKILL1 
button:5 mapped to KEY_SKILL3 
button:6 mapped to KEY_QUIT 
button:7 mapped to KEY_SERVICE 
button:8 mapped to KEY_COIN1 
button:9 mapped to KEY_START1 
button:10 mapped to KEY_QUIT 
button:11 mapped to KEY_PAUSE 
button:12 mapped to KEY_BUTTON1 
button:13 mapped to KEY_BUTTON2 
button:14 mapped to KEY_BUTTON3 
button:15 mapped to KEY_CONSOLE 
button:16 mapped to KEY_BUTTON1 
button:17 mapped to KEY_BUTTON1 
Framefile parse succeeded. Video/Audio directory is: /home/h/.daphne/singe/timegal/./
YUV overlay is done in software (ie unaccelerated).
Booting ROM ...
Starting Singe version 1.14
libpng warning: iCCP: profile 'ICC Profile': 1000000h: invalid rendering intent
libpng warning: iCCP: profile 'ICC Profile': 1000000h: invalid rendering intent
libpng warning: iCCP: profile 'ICC Profile': 1000000h: invalid rendering intent
libpng warning: iCCP: profile 'ICC Profile': 1000000h: invalid rendering intent
libpng warning: iCCP: profile 'ICC Profile': 1000000h: invalid rendering intent
libpng warning: iCCP: known incorrect sRGB profile
Search to 65212 received [blocking] 
Play
Successfully changed speed to 1/1X
Search to 3 received [blocking] 
Play
Pause
Search to 59536 received [blocking] 
Play
Successfully changed speed to 1/1X
SINGE: Game Settings Loaded.
SINGE: Initializing Time Gal Singe v1.1
libpng warning: iCCP: profile 'ICC Profile': 1000000h: invalid rendering intent
Search to 55845 received [blocking] 
Play
Successfully changed speed to 1/1X
SINGE: Script Error!
SINGE: error running function 'onOverlayUpdate': timegal.lua:1951: attempt to perform arithmetic on a nil value
SINGE: Script Error!
/home/h/.daphne/singe.sh: line 56:  9033 Segmentation fault      (core dumped) ./$DAPHNE_BIN singe vldp $FULLSCREEN -framefile $DAPHNE_SHARE/singe/$1/$1.txt -script $DAPHNE_SHARE/singe/$1/$1.singe -homedir $DAPHNE_SHARE -datadir $DAPHNE_SHARE -sound_buffer 2048 -noserversend -x 800 -y 600
DaphneLoader failed with an unknown exit code : 139.`

All the other Singe games seem to work fine.
Any idea whats going on?

**Comment by DirtBagXon** [comment]
Responded here: https://github.com/DirtBagXon/singe/issues/1
