### ISSUE TITLE
Singe fails to compile due to SDL error

### ISSUE THREAD

**Issue by Shoegzer** [DavidGriffith/daphne#18]
While daphne itself compiles fine, with current source 2a829021e2af275b8e8690861290ce9b2e0ca07e singe fails due to an SDL error:
```
$ make -f Makefile.linux_x64 
g++  -fPIC  -c -o singeproxy.o singeproxy.cpp
In file included from singeproxy.cpp:23:
singeproxy.h:35:10: fatal error: SDL/SDL_image.h: No such file or directory
   35 | #include <SDL/SDL_image.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: singeproxy.o] Error 1
```
Note that libsdl1.2-dev is installed.

Compiled using linux mint 20 (ubuntu 20.04 base/repo), kernel 5.4 and gcc 9.3.0.

@DirtBagXon any thoughts here?  Thanks.

Update: Nevermind, for some reason I was also missing libsdl-image1.2-dev.  Not sure why it missed the install the first time but I tried again and it worked, so singe compiles now.  Closing.

**Comment by DirtBagXon** [comment]
Glad you got it working, just as a heads up, beware the bytecode issue in singe on 'Time Gal' and 'Ninja Hayate' if you hadn't seen it already.

https://github.com/DirtBagXon/singe/tree/master/bytecode

**Comment by OzFalcon** [comment]
> Glad you got it working, just as a heads up, beware the bytecode issue in singe on 'Time Gal' and 'Ninja Hayate' if you hadn't seen it already.
> 
> https://github.com/DirtBagXon/singe/tree/master/bytecode

Great to see these titles working.
I noticed the singe files have "@hayate.singe.decompile" and the patches are for decompiled singe lua scripts.
What was used to decompile these bytecode files?

**Comment by DirtBagXon** [comment]
It was a while ago, I was playing with decompiling these, but it was detailed in this thread:

http://www.emuline.org/topic/1628-arcade-pc-daphne-singe-set-laser-disc/

Starts from about page 3 as I recall.

Edit: unluac.jar  from http://hg.code.sf.net/p/unluac/hgcode was the successful candidate.

Second edit: In case you hadn't noticed the bytecode is addressed in a separate repo, which houses a standalone Singe.

https://github.com/DirtBagXon/singe

It may address further issues, but as I recall both branches were working with the fixed bytecode.

**Comment by Shoegzer** [comment]
@DirtBagXon Thanks for the heads up.  I'll keep this in mind as I'm testing through your code.
