### ISSUE TITLE
Readme does not describe installation

### ISSUE THREAD

**Issue by hackerb9** [DavidGriffith/daphne#2]
Compilation works fine, but there is a missing step in README.md: **installation.** 

In order for the `run.sh` script to work, the `pics` and `sound` directories must copied into ~/.daphne/

    mkdir -p ~/.daphne
    cp -a pics sound ~/.daphne/

Also, depending upon the game, the user must find the rom file and the laser disk which are not included with Daphne and copy them into ~/.daphne/roms and ~/.daphne/vldp_dl/. 

It'd be nice if there was a description of how this is done and perhaps a link to Digital Leisure so one can purchase the DVD needed.

**Comment by dariocdj** [comment]
And another related issue can be how to integrate in retropie after compiling (i'm not using neither a raspberry nor a 32bit linux so i can't use binary from website). When i run daphne.bin in test mode it shows me only player 1 player 2 and some other things but no image and no idea of controls....

**Comment by hackerb9** [comment]
@dariocdj I think you might want to file two new bug reports as your issues will not be resolved once the readme.md is updated to describe installation and this bug is closed. 

However, as a fellow user, I can suggest a couple things. First, 32-bit binaries [work fine](https://wiki.debian.org/Multiarch) on 64-bit Linux. 

Second, look at the [daphne wiki](https://www.daphne-emu.com:9443/mediawiki/index.php/input) to find the answer to your question about controls. Once you know the answer, maybe write up the answer you wish you had found here and submit it as a new bug. Perhaps something like,

In order to...  | press this
--------------|-------------
start a game | `5 5 1`
play a game | arrow keys, ctrl, alt
