### ISSUE TITLE
fixed joystick issues

### ISSUE THREAD

**Issue by ghost** [DavidGriffith/daphne#4]
im not very good git just learning it just to let you know ive fixed the joystick demon issues all you need to do is grab the input.cpp from the src/io/ folder if you want the fixes details of changes are in the dapinput.ini

**Comment by DavidGriffith** [comment]
I'm not sure what you're suggesting.

**Comment by ghost** [comment]
https://github.com/RetroPie/daphne-emu/compare/retropie...grant2258:retropie

for details ill simplify it. The setup is designed to used defaults is any are set for the keyboard and joystick. That is fine for  a system like a psp or a console with fixed buttons. There is no real way to unset them the way its setup . The joystick_buttons_map[10] should be initialized to -1 (not set ) for any system that doesnt have fixed buttons. The other issue is the analogue joystick the left and right axis is missing a ==0 condition that cause left and right to not work if more than 2 axis are on gampad/joystick
