### ISSUE TITLE
Verify this is current source?

### ISSUE THREAD

**Issue by SpiralBrad** [DavidGriffith/daphne#4]
The version of Daphne that is included with DaphneDDL comes with a changelog stating it to be "v1.0.12".  Your source is from 1.0.7.

Was the newer version's source never made public? If not, maybe that changelog could be used to recreate the changes.

(The changelog I speak of shows 1.0.8 to be "The SINGE update" - I thought SINGE to be a fork, but maybe it was merged into Daphne at this point?  It's source is available as 1.0 but also does not match its current released version of 1.14. ...Yeesh this project began to be mishandled.)

**Comment by DavidGriffith** [comment]
It is not current source.  Shortly after I put that repo up, Matt's SVN repo was pointed out to me.  That contains source going up to 1.0.12.  That someone copied and translated it to Github and I've forked that Github repo.  My plan is to translate my changes to the fork and delete this repo.

**Comment by SpiralBrad** [comment]
Ahhh, great to hear the source for 1.0.12 is public. I was looking for it myself but not hard enough apparently.

I'll be on the lookout for the new repo. Thanks!
