### ISSUE TITLE
Pull request for trivial 'singe' library compile on 64bit Linux, with README.md and singe.sh updates

### ISSUE THREAD

**Issue by DirtBagXon** [DavidGriffith/daphne#7]
[singe_diff.txt](https://github.com/DavidGriffith/daphne/files/3935152/singe_diff.txt)

**Comment by DirtBagXon** [comment]
Interesting discussion on the **singe** supported games here:
http://megadb.tweakly.net/offline_reading/t3_6jci0z.html

**Comment by DirtBagXon** [comment]
Taking this SINGE installation further, I was also able to get the single library compiled via the above to read 32bit bytecode compiled LUA **.singe** files using some clues posted here: 

http://lua-users.org/lists/lua-l/2016-02/msg00176.html

A discussion of the findings are posted here:

http://www.emuline.org/topic/1628-arcade-pc-daphne-singe-set-laser-disc/?page=3

Will be happy to push the changes made if allowed...

**Comment by DavidGriffith** [comment]
I'd love to approve a pull, but I don't see it here.

**Comment by DirtBagXon** [comment]
Apologies, should be one there now, got there in the end :)

**Comment by DavidGriffith** [comment]
Pull approved.  Thanks!
